### ISSUE TITLE
Negative intent by default

### ISSUE THREAD

**Issue by sabatale** [navigateconsulting/eva#198]
**Is your feature request related to a problem? Please describe.**
"Note: It is mandatory to create an intent called 'negative' that holds all the negative intents i.e. 'No', 'Nope', etc."

**Describe the solution you'd like**
Is this a technical limitation? I don't really see why not creating this intent by default with a few words, at least to make sure the training does not fail because the admin did not read the guide or missed that part.

**Comment by saikiran2603** [comment]
By Default , when a project is created , [twoStageFallbackPolicy](https://rasa.com/docs/rasa/core/policies/#two-stage-fallback-policy) is applied. You can check that in projects page in Properties.

`      name: "TwoStageFallbackPolicy"
      nlu_threshold: 0.3
      core_threshold: 0.3
      fallback_core_action_name: "action_default_fallback"
      fallback_nlu_action_name: "my_fallback_action"
      deny_suggestion_intent_name: "negative"`

here the last line mentions the default intent name which is required while applying this policy. 

If two stage fall back is not required, then this line can be removed and the project would not ask for default intents to be present before starting the training. As of now this behavior is not working as expected, and even if the policy is removed the validation checks for negative intent. Will make a fix which will only check for default intents and actions if a corresponding policy is applied. 

As for creating this intent by default. I think it would be better to keep this flexibility of renaming the deafult intent for negative and adding it in properties. Once we add validations and modify the error messages to explain the issue properly i think this should be good to go. 
 
Thanks for pointing this out !! :)
