### ISSUE TITLE
Can't get bot to answer anything

### ISSUE THREAD

**Issue by sabatale** [navigateconsulting/eva#199]
**Describe the bug**
I can't get the bot to give any type of response:

![image](https://user-images.githubusercontent.com/50220345/84185519-1fc66e80-aa5d-11ea-9faa-86327914b85c.png)

**To Reproduce**
Mapped entity greet to intent greet:
![image](https://user-images.githubusercontent.com/50220345/84185548-2d7bf400-aa5d-11ea-9382-a1d14955f2a5.png)

Set responses for utter_greet:
![image](https://user-images.githubusercontent.com/50220345/84185588-3bca1000-aa5d-11ea-8144-647aca9d882d.png)

I've created a story (is this necessary?), trained and previewed the model. No errors.

Did I forget something?

**Expected behavior**
The bot should answer "hi" or any responses from utter_greet.

**Desktop (please complete the following information):**
Latest build on Ubuntu.

**Comment by saikiran2603** [comment]
Could you share the story which you created ?

**Comment by saikiran2603** [comment]
Can you try the base domain and see if it works in try now mode ?

**Comment by saikiran2603** [comment]
I tried to build a similar project, 

Intent : greet 

![image](https://user-images.githubusercontent.com/42929961/84254364-c29aed80-ab2e-11ea-9fa8-a68f755cffdd.png)

Response 
![image](https://user-images.githubusercontent.com/42929961/84254419-d3e3fa00-ab2e-11ea-8404-f6c6bf834342.png)

and a story 

![image](https://user-images.githubusercontent.com/42929961/84254452-e100e900-ab2e-11ea-8e76-2f2488ae1873.png)

This seems to be working 

![image](https://user-images.githubusercontent.com/42929961/84254628-17d6ff00-ab2f-11ea-8d8d-722a9268963c.png)

In the project  properties ,  below were the settings , 

---
  language: "en"
  pipeline: "supervised_embeddings"
  policies: 
    - 
      name: "KerasPolicy"
      epochs: 150
      max_history: 4
    - 
      name: "MemoizationPolicy"
    - 
      name: "MappingPolicy"

![image](https://user-images.githubusercontent.com/42929961/84254729-3d640880-ab2f-11ea-9be7-ad294dd59303.png)

Could you try the same at your end ? Also please confirm the version you are using ? There have been some major changes in the code base recently.
